export const TECH_TAGS = {
  REACT: "React",
  D3JS: "D3.js",
  TYPESCRIPT: "TypeScript",
  NEXTJS: "Next.js",
  OPENAI: "OpenAI",
  LLM: "LLM",
  OCR: "OCR",
  FACENET: "Facenet",
  TAILWIND: "Tailwind",
  TAILWIND_CSS: "Tailwind CSS",
  THREEJS: "Three.js",
  R3F: "R3F",
  WEBGL: "WebGL",
  WEBRTC: "WebRTC",
  VUEJS: "Vue.js",
  FIREBASE: "Firebase",
  PWA: "PWA",
  NODEJS: "Node.js",
  GRAPHQL: "GraphQL",
  POSTGRESQL: "PostgreSQL",
  CPP: "C++",
  JAVA: "Java",
  GO: "Go",
  PYTHON: "Python",
  SVELTEKIT: "SvelteKit",
  KUBERNETES: "Kubernetes",
  JENKINS: "Jenkins",
  ARGOCD: "ArgoCD",
  AWS: "AWS",
  GCP: "GCP",
  DOCKER: "Docker",
  SPRING_BOOT: "Spring Boot",
  MYSQL: "MySQL",
  LINUX: "Linux",
  REDIS: "Redis",
  RABBITMQ: "RabbitMQ",
  KAFKA: "Kafka",
  ELASTICSEARCH: "Elasticsearch",
  PROMETHEUS: "Prometheus",
  GRAFANA: "Grafana",
  TERRAFORM: "Terraform",
  GITHUB_ACTIONS: "GitHub Actions",
  NGINX: "Nginx",
  MSA: "MSA",
  SLAM: "SLAM",
  GITLAB: "GitLab",
  GITHUB: "GitHub",
  JIRA: "Jira",
  MATTERMOST: "Mattermost",
  DOORAY: "Dooray",
  GIN: "Gin",
  ECHO: "Echo",
} as const;
